const stage1 = [
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 1,
    StageName: "Kilo XP",
    Bib: 2,
    Firstname: "Lucie",
    Lastname: "Jolivet",
    Gender: "F",
    Club: "BEAUNE TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior F",
    Status: "",
    StartTime: "16:00:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "5:09",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "6:14",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "8:17",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "10:25",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "12:33",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "16:45",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "16:45",
    CurrentSplitGap: "-",
    Swim: "5:09",
    Transition: "1:05",
    Run: "10:31",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 1,
    StageName: "Kilo XP",
    Bib: 23,
    Firstname: "Louis",
    Lastname: "Billault",
    Gender: "M",
    Club: "CLERMONT TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "16:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "5:35",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "6:52",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "9:07",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "11:22",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "13:34",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "18:02",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "18:02",
    CurrentSplitGap: "-",
    Swim: "5:35",
    Transition: "1:17",
    Run: "11:10",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 1,
    StageName: "Kilo XP",
    Bib: 22,
    Firstname: "Julien",
    Lastname: "Marimoutou",
    Gender: "M",
    Club: "TRIATHLON BARRABAN",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "16:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 2,
    Split1Time: "5:38",
    Split1Gap: "+0:03",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 2,
    Split2Time: "6:58",
    Split2Gap: "+0:06",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 2,
    Split3Time: "9:17",
    Split3Gap: "+0:10",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 2,
    Split4Time: "11:34",
    Split4Gap: "+0:12",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 2,
    Split5Time: "13:54",
    Split5Gap: "+0:20",
    FinishName: "Arrivée",
    FinishRank: 2,
    FinishTime: "18:33",
    FinishGap: "+0:31",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 2,
    CurrentSplitTime: "18:33",
    CurrentSplitGap: "+0:31",
    Swim: "5:38",
    Transition: "1:20",
    Run: "11:35",
  },
];

const stage2 = [
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 2,
    StageName: "Mega XP",
    Bib: 2,
    Firstname: "Lucie",
    Lastname: "Jolivet",
    Gender: "F",
    Club: "BEAUNE TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior F",
    Status: "",
    StartTime: "17:05:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "2:06",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "4:13",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "6:21",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "8:29",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "10:32",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "14:48",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "14:48",
    CurrentSplitGap: "-",
    Swim: "2:06",
    Transition: "2:07",
    Run: "10:35",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 2,
    StageName: "Mega XP",
    Bib: 23,
    Firstname: "Louis",
    Lastname: "Billault",
    Gender: "M",
    Club: "CLERMONT TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "17:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "2:12",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "4:25",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "6:38",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "8:54",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "11:06",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "15:32",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "15:32",
    CurrentSplitGap: "-",
    Swim: "2:12",
    Transition: "2:13",
    Run: "11:07",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 2,
    StageName: "Mega XP",
    Bib: 22,
    Firstname: "Julien",
    Lastname: "Marimoutou",
    Gender: "M",
    Club: "TRIATHLON BARRABAN",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "17:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 2,
    Split1Time: "2:16",
    Split1Gap: "+0:04",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 2,
    Split2Time: "4:36",
    Split2Gap: "+0:11",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 2,
    Split3Time: "6:53",
    Split3Gap: "+0:15",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 2,
    Split4Time: "9:12",
    Split4Gap: "+0:18",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 2,
    Split5Time: "11:29",
    Split5Gap: "+0:23",
    FinishName: "Arrivée",
    FinishRank: 2,
    FinishTime: "16:05",
    FinishGap: "+0:33",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 2,
    CurrentSplitTime: "16:05",
    CurrentSplitGap: "+0:33",
    Swim: "2:16",
    Transition: "2:20",
    Run: "11:29",
  },
];

const stage3 = [
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 3,
    StageName: "Giga XP",
    Bib: 2,
    Firstname: "Lucie",
    Lastname: "Jolivet",
    Gender: "F",
    Club: "BEAUNE TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior F",
    Status: "",
    StartTime: "18:10:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "2:06",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "4:14",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "6:21",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "8:29",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "10:32",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "14:45",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "14:45",
    CurrentSplitGap: "-",
    Swim: "2:06",
    Transition: "2:08",
    Run: "10:31",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 3,
    StageName: "Giga XP",
    Bib: 23,
    Firstname: "Louis",
    Lastname: "Billault",
    Gender: "M",
    Club: "CLERMONT TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "18:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "2:14",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "4:31",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "6:44",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "9:02",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "11:18",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "15:50",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "15:50",
    CurrentSplitGap: "-",
    Swim: "2:14",
    Transition: "2:17",
    Run: "11:19",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 3,
    StageName: "Giga XP",
    Bib: 22,
    Firstname: "Julien",
    Lastname: "Marimoutou",
    Gender: "M",
    Club: "TRIATHLON BARRABAN",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "18:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 2,
    Split1Time: "2:20",
    Split1Gap: "+0:06",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 2,
    Split2Time: "4:36",
    Split2Gap: "+0:05",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 2,
    Split3Time: "6:56",
    Split3Gap: "+0:12",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 2,
    Split4Time: "9:15",
    Split4Gap: "+0:13",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 2,
    Split5Time: "11:35",
    Split5Gap: "+0:17",
    FinishName: "Arrivée",
    FinishRank: 2,
    FinishTime: "16:18",
    FinishGap: "+0:28",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 2,
    CurrentSplitTime: "16:18",
    CurrentSplitGap: "+0:28",
    Swim: "2:20",
    Transition: "2:16",
    Run: "11:42",
  },
];

const stage4 = [
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 4,
    StageName: "Tera XP",
    Bib: 2,
    Firstname: "Lucie",
    Lastname: "Jolivet",
    Gender: "F",
    Club: "BEAUNE TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior F",
    Status: "",
    StartTime: "19:15:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "2:08",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "4:11",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "6:19",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "8:27",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "10:34",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "14:45",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "14:45",
    CurrentSplitGap: "-",
    Swim: "2:08",
    Transition: "2:03",
    Run: "10:34",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 4,
    StageName: "Tera XP",
    Bib: 23,
    Firstname: "Louis",
    Lastname: "Billault",
    Gender: "M",
    Club: "CLERMONT TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "19:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 1,
    Split1Time: "2:15",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "4:27",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 1,
    Split3Time: "6:43",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "8:59",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 1,
    Split5Time: "11:13",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: 1,
    FinishTime: "15:42",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "15:42",
    CurrentSplitGap: "-",
    Swim: "2:15",
    Transition: "2:12",
    Run: "11:15",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 4,
    StageName: "Tera XP",
    Bib: 22,
    Firstname: "Julien",
    Lastname: "Marimoutou",
    Gender: "M",
    Club: "TRIATHLON BARRABAN",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "19:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: 2,
    Split1Time: "2:20",
    Split1Gap: "+0:05",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 2,
    Split2Time: "4:40",
    Split2Gap: "+0:13",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: 2,
    Split3Time: "6:59",
    Split3Gap: "+0:16",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 2,
    Split4Time: "9:19",
    Split4Gap: "+0:20",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: 2,
    Split5Time: "11:39",
    Split5Gap: "+0:26",
    FinishName: "Arrivée",
    FinishRank: 2,
    FinishTime: "16:16",
    FinishGap: "+0:34",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 2,
    CurrentSplitTime: "16:16",
    CurrentSplitGap: "+0:34",
    Swim: "2:20",
    Transition: "2:20",
    Run: "11:36",
  },
];

const stage5 = [
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 5,
    StageName: "Peta XP",
    Bib: 2,
    Firstname: "Lucie",
    Lastname: "Jolivet",
    Gender: "F",
    Club: "BEAUNE TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior F",
    Status: "",
    StartTime: "20:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: "",
    Split1Time: "12:25",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "14:29",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: "",
    Split3Time: "16:36",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "18:43",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: "",
    Split5Time: "20:50",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: "",
    FinishTime: "25:05",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "25:05",
    CurrentSplitGap: "-",
    Swim: "12:25",
    Transition: "2:04",
    Run: "10:36",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 5,
    StageName: "Peta XP",
    Bib: 22,
    Firstname: "Julien",
    Lastname: "Marimoutou",
    Gender: "M",
    Club: "TRIATHLON BARRABAN",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "20:22:06",
    Split1Name: "Sortie Natation",
    Split1Rank: "",
    Split1Time: "11:05",
    Split1Gap: "-",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 1,
    Split2Time: "13:26",
    Split2Gap: "-",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: "",
    Split3Time: "15:47",
    Split3Gap: "-",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 1,
    Split4Time: "18:10",
    Split4Gap: "-",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: "",
    Split5Time: "20:28",
    Split5Gap: "-",
    FinishName: "Arrivée",
    FinishRank: "",
    FinishTime: "25:13",
    FinishGap: "-",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 1,
    CurrentSplitTime: "25:13",
    CurrentSplitGap: "-",
    Swim: "11:05",
    Transition: "2:21",
    Run: "11:47",
  },
  {
    Report: "Live Stage Results",
    ContestID: 2,
    ContestName: "YOTTA XP",
    StageID: 5,
    StageName: "Peta XP",
    Bib: 23,
    Firstname: "Louis",
    Lastname: "Billault",
    Gender: "M",
    Club: "CLERMONT TRIATHLON",
    Firstname2: "",
    Lastname2: "",
    Gender2: "",
    Club2: "",
    TeamName: "",
    Category: "Senior M",
    Status: "",
    StartTime: "20:20:00",
    Split1Name: "Sortie Natation",
    Split1Rank: "",
    Split1Time: "13:23",
    Split1Gap: "+2:18",
    Split2Name: "Départ Course à Pied",
    Split2Rank: 2,
    Split2Time: "15:37",
    Split2Gap: "+2:11",
    Split3Name: "Course à pied - 2 km",
    Split3Rank: "",
    Split3Time: "17:51",
    Split3Gap: "+2:04",
    Split4Name: "Course à Pied - Fin Tour 1",
    Split4Rank: 2,
    Split4Time: "20:06",
    Split4Gap: "+1:56",
    Split5Name: "Course à pied - 6 km",
    Split5Rank: "",
    Split5Time: "22:18",
    Split5Gap: "+1:50",
    FinishName: "Arrivée",
    FinishRank: "",
    FinishTime: "26:43",
    FinishGap: "+1:30",
    CurrentSplitName: "Arrivée",
    CurrentSplitRank: 2,
    CurrentSplitTime: "26:43",
    CurrentSplitGap: "+1:30",
    Swim: "13:23",
    Transition: "2:14",
    Run: "11:06",
  },
];
